version: '3.4'

services:
  rabbitmqlistner:
    image: rabbitmqlistner
    build:
      context: .
      dockerfile: src/RabbitMQListner/Dockerfile

  rabbitmqsender:
    image: rabbitmqsender
    build:
      context: .
      dockerfile: src/RabbitMQSender/Dockerfile

networks:
  my-network:
    driver: bridge